# Generated by Django 4.2.4 on 2023-08-22 15:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import reviews.utils
import reviews.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, editable=False)),
                ('title', models.CharField(help_text='Добавьте название', max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Укажите адрес для категории', unique=True, verbose_name='Адрес для категории')),
                ('img', models.ImageField(blank=True, help_text='Выберите изображение категории', null=True, upload_to=reviews.utils.get_path_upload_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), reviews.validators.validate_image_size], verbose_name='Изображение категории')),
                ('active', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='reviews.category', verbose_name='Надкатегория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, editable=False)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, editable=False)),
                ('title', models.CharField(help_text='Добавьте название', max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка на продукт/услугу')),
                ('active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='reviews.category', verbose_name='Категория продукта/услуги')),
            ],
            options={
                'verbose_name': 'Продукт/Услуга',
                'verbose_name_plural': 'Продукты/Услуги',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, editable=False)),
                ('title', models.CharField(help_text='Добавьте название', max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('text', models.TextField(help_text='Добавьте текст отзыва', verbose_name='Текст отзыва')),
                ('recommendation', models.BooleanField(default=False, verbose_name='Рекомендуете друзьям?')),
                ('price', models.IntegerField(blank=True, help_text='сум (только цифры без пробелов и запятых)', null=True, verbose_name='Стоимость, например: 100 000 (необязательно)')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('upd_date', models.DateTimeField(auto_now=True, verbose_name='Отредактировано')),
                ('image', models.ImageField(blank=True, help_text='Выберите изображение', null=True, upload_to=reviews.utils.get_path_upload_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), reviews.validators.validate_image_size], verbose_name='Изображение')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Средне'), (4, 'Хорошо'), (5, 'Отлично')], default=3, verbose_name='Оценка')),
                ('pluses', models.TextField(help_text='Достоинства', verbose_name='Достоинства')),
                ('minuses', models.TextField(help_text='Недостатки', verbose_name='Недостатки')),
                ('is_active', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('location', models.CharField(max_length=50, verbose_name='Расположение объекта')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, editable=False)),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.chat')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, editable=False)),
                ('text', models.TextField(help_text='Добавьте текст комментария', verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('active', models.BooleanField(default=False, verbose_name='Одобрен?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='reviews.comment')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, editable=False)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, editable=False)),
                ('image', models.ImageField(upload_to=reviews.utils.get_path_upload_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])], verbose_name='Фото')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='reviews.review')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique subscriptions'),
        ),
    ]
