# Generated by Django 4.2.4 on 2023-08-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_category_slug_remove_product_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='is_draft',
            new_name='draft',
        ),
    ]
