# Generated by Django 4.2.4 on 2023-08-27 16:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_additionalimage_deleted_bookmark_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='minuses',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pluses',
        ),
        migrations.AddField(
            model_name='review',
            name='minuses',
            field=models.ManyToManyField(to='reviews.minus', verbose_name='Недостатки'),
        ),
        migrations.AddField(
            model_name='review',
            name='pluses',
            field=models.ManyToManyField(to='reviews.plus', verbose_name='Достоинства'),
        ),
    ]
